global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: otel-tutorial

scrape_configs:
  # Prometheus self monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    metrics_path: '/metrics'

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: '/metrics'

  # Application metrics scraped from the host
  - job_name: 'rust-app'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
