server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker scrape config - captures container stdout/stderr
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          env: dev
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_image_name']
        target_label: 'image'

  # Host application logs written to logs/app.log
  - job_name: rust-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: rust-app
          env: dev
          __path__: /var/log/otel-tutorial/app.log
