server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

# Scrape all Loki's logs from Docker
clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker scrape config
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          env: dev
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_image_name']
        target_label: 'image'

  # System logs
  - job_name: varlog
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlog
          __path__: /var/log/*log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
      - labels:
          level:
          message:
